---
title: "plots for thesis presentation"
author: "Megan Hepner"
date: "October 12, 2017"
output: html_document
---

```{r ntmr}

all_matrices_data = read_rds("psu_matrices_data_rds")

matrices_ntmr = all_matrices_data %>% 
    group_by(YEAR, PROT) %>% #add subregion later 
    summarize(
      richness_mean = mean(richness),
      richness_n = length(richness),
      richness_sd = sd(richness),
      richness_se = richness_sd / sqrt(richness_n),
      richness_min = min(richness),
      richness_max = max(richness),
      simpson_mean = mean(simpson),
      simpson_n = length(simpson),
      simpson_sd = sd(simpson),
      simpson_se = simpson_sd / sqrt(simpson_n),
      simpson_min = min(simpson),
      simpson_max = max(simpson),
      func.div_mean = mean(func.div),
      func.div_n = length(func.div),
      func.div_sd = sd(func.div),
      func.div_se = func.div_sd / sqrt(func.div_n),
      func.div_min = min(func.div),
      func.div_max = max(func.div))

rich_prot = ggplot(matrices_ntmr,aes(x=YEAR,y=richness_mean, colour=factor(PROT), group=factor(PROT)))+ 
  geom_line(aes(group=PROT),lwd=1.2) +
  geom_point(size=4) +
  geom_errorbar(aes(ymax=richness_mean+richness_se,ymin=richness_mean-richness_se),width=0.3)+
  labs(title= "Richness", x="Year", y="Mean Effective \nNumber of Species (± SE)", color = NULL)+
  scale_color_manual(
    values =  c("#3FD300","#9400D3"),
    breaks = c("1", "0"), 
    labels=c("Protected","Not Protected"))+
  scale_x_continuous(
    limits = c(1999, 2016), 
    breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016),
    labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme_bw() +
  theme(
    legend.position="bottom",
    legend.text =element_text(size=20,color="black"),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=20),
    axis.text.x =element_text(size=16, color="black"),
    axis.title.y=element_text(size=20),
    axis.text.y =element_text(size=16, color="black"),
    panel.border =element_rect(size = 1),
    plot.title =element_text(hjust = 0, size =22))
ggsave(file="richness_by_year_PROT_bw2.png", path="big_csv/plots")
#ggsave(file="richness_by_year_PROT_bw.pdf", path="big_csv/plots")

#simpson
simp_prot = ggplot(matrices_ntmr,aes(x=YEAR,y=simpson_mean, colour=factor(PROT), group=factor(PROT)))+ 
  geom_line(aes(group=PROT),lwd=1.2) +
  geom_point(size=4) +
  geom_errorbar(aes(ymax=simpson_mean+simpson_se,ymin=simpson_mean-simpson_se),width=0.3)+
  labs(title= "Simpson", x="Year", y="Mean Effective \nNumber of Species (± SE)", color = NULL)+
  scale_color_manual(
    values =  c("#3FD300","#9400D3"),
    breaks = c("1", "0"), 
    labels=c("Protected","Not Protected"))+
  scale_x_continuous(
    limits = c(1999, 2016), 
    breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016),
    labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme_bw()+
  theme(
    legend.position="bottom",
    legend.text =element_text(size=20,color="black"),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=20),
    axis.text.x =element_text(size=16, color="black"),
    axis.title.y=element_text(size=20),
    axis.text.y =element_text(size=16, color="black"),
    panel.border =element_rect(size = 1),
    plot.title =element_text(hjust = 0, size =22))
ggsave(file="simpson_by_year_PROT_bw.png", path="big_csv/plots")
#ggsave(file="simpson_diversity_by_year_PROT_bw.pdf", path="big_csv/plots")

#functional
func_prot = ggplot(matrices_ntmr,aes(x=YEAR,y=func.div_mean, colour=factor(PROT), group=factor(PROT)))+ 
  geom_line(aes(group=PROT),lwd=1.2) +
  geom_point(size=4) +
  geom_errorbar(aes(ymax=func.div_mean+func.div_se,ymin=func.div_mean-func.div_se),width=0.3)+
  labs(title= "Functional", x="Year", y="Mean Effective \nNumber of Species (± SE)", color = NULL)+
  scale_color_manual(
    values =  c("#3FD300","#9400D3"),
    breaks = c("1", "0"), 
    labels=c("Protected","Not Protected"))+
  scale_x_continuous(
    limits = c(1999, 2016), 
    breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016),
    labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme_bw()+
  theme(
    legend.position="bottom",
    legend.text =element_text(size=20,color="black"),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=20),
    axis.text.x =element_text(size=16, color="black"),
    axis.title.y=element_text(size=20),
    axis.text.y =element_text(size=16, color="black"),
    panel.border =element_rect(size = 1),
    plot.title =element_text(hjust = 0, size =22))
ggsave(file="functional_by_year_PROT_bw.png", path="big_csv/plots")

ntmr_plot = grid.arrange(rich_prot,simp_prot,func_prot,ncol=3)
ggsave(file="ntmr_plots2.png", ntmr_plot, width=10, height=5, path="big_csv/plots")

```

```{r strat all}

 matrices_strat_grouped = all_matrices_data %>% 
    mutate(
      STRAT_GROUPED = 
      ifelse(grepl("FMLR|FSLR|FDLR", STRAT), 'LINEAR_REEF', 
             ifelse(grepl("OFPR|MCPR|INPR", STRAT), 'PATCH_REEF',
                    ifelse(grepl('HRRF', STRAT), 'HIGH_RELIEF', "IDK")))) %>%
    group_by(YEAR, STRAT_GROUPED) %>% 
    summarize(
      richness_mean = mean(richness),
      richness_n = length(richness),
      richness_sd = sd(richness),
      richness_se = richness_sd / sqrt(richness_n),
      simpson_mean = mean(simpson),
      simpson_n = length(simpson),
      simpson_sd = sd(simpson),
      simpson_se = simpson_sd / sqrt(simpson_n),
      func.div_mean = mean(func.div),
      func.div_n = length(func.div),
      func.div_sd = sd(func.div),
      func.div_se = func.div_sd / sqrt(func.div_n))
  
library(colortools)

#richness
rich_ys = ggplot(matrices_strat_grouped,aes(x=YEAR,y=richness_mean, colour=STRAT_GROUPED, group=STRAT_GROUPED))+ 
  geom_line(aes(group=STRAT_GROUPED),lwd=1.2) +
  geom_point(size=4) +
  geom_errorbar(aes(ymin=richness_mean-richness_se, ymax=richness_mean+richness_se), width=.3)+
  labs(title= "Richness", x="Year", y="Mean Effective \nNumber of Species (± SE)", colour = "")+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  scale_color_manual(name="", 
                  labels= c("High reef", "Linear reef", "Patch reef"),
                  values=c("#FF0000","#0000FF","#00FF00"))+ 
  theme_bw()+
  theme(
    legend.position="bottom",
    legend.text =element_text(size=20,color="black"),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=20),
    axis.text.x =element_text(size=16, color="black"),
    axis.title.y=element_text(size=20),
    axis.text.y =element_text(size=16, color="black"),
    panel.border =element_rect(size = 1),
    plot.title =element_text(hjust = 0, size =22))
ggsave(file="richness_by_year_and_strata2.png", path="big_csv/plots")

#simpson
simp_ys = ggplot(matrices_strat_grouped,aes(x=YEAR,y=simpson_mean, colour=STRAT_GROUPED, group=STRAT_GROUPED))+ #shape=STRAT
  geom_line(aes(group=STRAT_GROUPED),lwd=1.2) +
  geom_point(size=4) +
  geom_errorbar(aes(ymin=simpson_mean-simpson_se, ymax=simpson_mean+simpson_se), width=.3)+
  labs(title= "Simpson", x="Year", y="Mean Effective \nNumber of Species (± SE)", colour = "")+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  scale_color_manual(name="", 
                     labels= c("High reef", "Linear reef", "Patch reef"),
                  values=c("#FF0000","#0000FF","#00FF00"))+
  theme_bw()+
  theme(
    legend.position="bottom",
    legend.text =element_text(size=20,color="black"),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=20),
    axis.text.x =element_text(size=16, color="black"),
    axis.title.y=element_text(size=20),
    axis.text.y =element_text(size=16, color="black"),
    panel.border =element_rect(size = 1),
    plot.title =element_text(hjust = 0, size =22))
ggsave(file="simpson_by_year_and_strata2.png", path="big_csv/plots")

#functional
func_ys = ggplot(matrices_strat_grouped,aes(x=YEAR,y=func.div_mean, colour=STRAT_GROUPED, group=STRAT_GROUPED))+ #shape=STRAT
  geom_line(aes(group=STRAT_GROUPED),lwd=1.2) +
  geom_point(size=4) +
  geom_errorbar(aes(ymin=func.div_mean-func.div_se, ymax=func.div_mean+func.div_se), width=.3)+
  labs(title= "Functional", x="Year", y="Mean Effective \nNumber of Species (± SE)", colour = "")+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  scale_color_manual(name="", labels= c("High reef", "Linear reef", "Patch reef"),values=c("#FF0000","#0000FF","#00FF00"))+
  theme_bw()+
  theme(
    legend.position="bottom",
    legend.text =element_text(size=20,color="black"),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=20),
    axis.text.x =element_text(size=16, color="black"),
    axis.title.y=element_text(size=20),
    axis.text.y =element_text(size=16, color="black"),
    panel.border =element_rect(size = 1),
    plot.title =element_text(hjust = 0, size =22))
ggsave(file="functional_by_year_and_strata2.png", path="big_csv/plots")
#ggsave(file="functional_by_year_and_strata.pdf", path="big_csv/plots", width=7, height=7)
```

```{r subregion}

#richness
rich_g= ggplot(matrices_strat_grouped_with_subregion,aes(x=YEAR,y=richness_mean, colour=SUBREGION_DOMAIN, group=SUBREGION_DOMAIN))+ #shape=STRAT
  geom_line(aes(group=SUBREGION_DOMAIN),lwd=1) +
  geom_point(size=3) +
 geom_errorbar(aes(ymin=richness_mean-richness_se, ymax=richness_mean+richness_se), width=.1)+
  labs(title= "Richness", x="Year", y="Mean ENS", colour = "")+
  scale_colour_manual(labels=c("Lower Keys", "Middle Keys", "Upper Keys"), values= c("cyan", "deeppink", "yellow"))+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme(
    legend.position="bottom", #right 
    legend.text=element_text(size=11, color = "white"),
    legend.key.size=unit(5,"mm"),
    legend.background = element_rect(fill = "grey30"),
    panel.background=element_rect(fill="grey30"), #black
    panel.grid.major=element_line("grey40"),#element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=12),
    axis.title.y=element_text(size=12),
    plot.title =element_text(hjust = 0),
    title=element_text(size=12))
ggsave(file="richness_subregion.png", path="big_csv/plots")
ggsave(file="richness_subregion.pdf", path="big_csv/plots")

#simpson
sim_g= ggplot(matrices_strat_grouped_with_subregion,aes(x=YEAR,y=simpson_mean, colour=SUBREGION_DOMAIN, group=SUBREGION_DOMAIN))+ #shape=STRAT
  geom_line(aes(group=SUBREGION_DOMAIN),lwd=1) +
  geom_point(size=3) +
  geom_errorbar(aes(ymin=simpson_mean-simpson_se, ymax=simpson_mean+simpson_se), width=.1)+
  labs(title= "Simpson", x="Year", y="Mean ENS", colour = "")+
  scale_colour_manual(labels=c("Lower Keys", "Middle Keys", "Upper Keys"), values= c("cyan", "deeppink", "yellow"))+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme(
    legend.position="bottom", #right 
    legend.text=element_text(size=11, color = "white"),
    legend.key.size=unit(5,"mm"),
    legend.background = element_rect(fill = "grey30"),
    panel.background=element_rect(fill="grey30"), #black
    panel.grid.major=element_line("grey40"),#element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=12),
    axis.title.y=element_text(size=12),
    plot.title =element_text(hjust = 0),
    title=element_text(size=12))
ggsave(file="simpson__subregion.png", path="big_csv/plots")
ggsave(file="simpson__subregion.pdf", path="big_csv/plots")

#functional
func_g= ggplot(matrices_strat_grouped_with_subregion,aes(x=YEAR,y=func.div_mean, colour=SUBREGION_DOMAIN, group=SUBREGION_DOMAIN))+ #shape=STRAT
  geom_line(aes(group=SUBREGION_DOMAIN),lwd=1) +
  geom_point(size=3) +
  geom_errorbar(aes(ymax=func.div_mean+func.div_se,ymin=func.div_mean-func.div_se),width=0.1)+
  labs(title= "Functional", x="Year", y="Mean ENS", colour = "")+
  scale_colour_manual(labels=c("Lower Keys", "Middle Keys", "Upper Keys"), values= c("cyan", "deeppink", "yellow"))+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme(
    legend.position="bottom", #right 
    legend.text=element_text(size=11, color = "white"),
    legend.key.size=unit(5,"mm"),
    legend.background = element_rect(fill = "grey30"),
    panel.background=element_rect(fill="grey30"), #black
    panel.grid.major=element_line("grey40"),#element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=12),
    axis.title.y=element_text(size=12),
    plot.title =element_text(hjust = 0),
    title=element_text(size=12))
ggsave(file="functional_subregion.png", path="big_csv/plots")
ggsave(file="functional_subregion.pdf", path="big_csv/plots")

#save legend
for_legend_g <- get_legend(rich_g)
```

```{r comparing diversity}

#Melt dataframe so diversity indices are in a single column
  x = reshape2::melt(all_matrices_data, id.vars = c("YEAR"),
                     measure.vars=c("richness","simpson","func.div")) 
#Summarize means and SEs by year and variable
  
x=plyr::ddply(x, c("YEAR", "variable"), summarize, value.mean=mean(value), value.se=plotrix::std.error(value))
#Rename levels for figure plotting
  levels(x$variable)=c("Richness","Simpson", "Functional")
  diversity_plot = x %>%
    as.tibble()

  diversity_year_plot = diversity_plot %>% 
    ggplot(.,aes(x=YEAR, y=value.mean, color=variable))+
    geom_errorbar(aes(ymax=value.mean+value.se,ymin=value.mean-value.se),width=0.3)+
    geom_point(size=3)+
    geom_line(aes(group=variable),lwd=1)+
    labs(title= "Florida Keys Reef Fish Biodiversity", x="Year", y="Mean Effective \nNumber of Species (± SE)", colour = "")+
    scale_y_continuous(limits= c(0,50),
                       breaks=c(0,5,10,15,20,25,30,35,40,45,50), 
                       labels=c("0","","10","","20","","30","","40","","50"))+
    scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  scale_color_manual(
    labels= c("Richness","Simpson diversity","Functional diversity"), 
    values=c("Richness"="deeppink","Simpson"="cyan","Functional"="green"))+ 
  #theme_bw()+
  theme(
    legend.position="bottom",
    legend.background = element_rect(fill="black"),
    legend.text =element_text(size=18,color="white"),
    panel.background=element_rect(fill="black"), #black
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=18),
    axis.text.x =element_text(size=14),
    axis.title.y=element_text(size=18),
    axis.text.y =element_text(size=14),
    plot.title =element_text(hjust = 0, size =20))
ggsave(file="diversity_plot2.png", path="big_csv/plots")

sggsave(file="diversity_plot.png", path="big_csv/plots")  
ggsave(file="diversity_plot.pdf", path="big_csv/plots")

#save legend
for_legend_rssf <- get_legend(diversity_year_plot)
ggsave(file="legend_diversity.png", for_legend_rssf, width =7, height=7, path="big_csv/plots")

diversity_simp_shan_func = diversity_plot %>% 
  filter(variable != "Richness") %>%
  filter(variable != "Shannon")
  as.tibble()
  
simp_func_plot =  
    ggplot(diversity_simp_shan_func, aes(x=YEAR, y=value.mean, color=variable))+
    geom_errorbar(aes(ymax=value.mean+value.se,ymin=value.mean-value.se),width=0.2)+
    geom_point(size=3)+
    geom_line(aes(group=variable),lwd=1)+
    labs(title= "Florida Keys Reef Fish Biodiversity", x="Year", y="Effective Number of Species", colour = "")+
    scale_y_continuous(limits= c(2,10),
                       breaks=c(2,4,6,8,10), 
                       labels=c("2","4","6","8","10"))+
    scale_x_continuous(limits = c(1999, 2016), 
                       breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), 
                       labels=c("2000","2002","2004","2006","2008","2010","2012","2014","2016"))+
  scale_color_manual(
    labels= c("Simpson diversity","Functional diversity"),
    values=c("Simpson"="green",
             "Functional"="cyan"))+
  #theme_bw()+
  theme(
    legend.position="bottom", #right 
    legend.text=element_text(size=11, color = "white"),
    legend.key.size=unit(5,"mm"),
    legend.background = element_rect(fill = "grey30"),
    panel.background=element_rect(fill="grey30"), #black
    panel.grid.major=element_line("grey40"),#element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=12),
    axis.title.y=element_text(size=12),
    plot.title =element_text(hjust = 0),
    title=element_text(size=12))

ggsave(file="diversity_sf.png", path="big_csv/plots")
ggsave(file="diversity_ssf.png", path="big_csv/plots")
ggsave(file="diversity_ssf.pdf", path="big_csv/plots")

#save legend
for_legend_ssf <- get_legend(simp_shan_func_plot)
ggsave(file="legend_diversity2.png", for_legend_ssf, width =7, height=7, path="big_csv/plots")

```

```{r drivers plot}

partial_deviance_list = read_csv("partial_deviance_list.csv")

partial_deviance_list = partial_deviance_list %>%
  filter(Diversity != "Abundance")%>%
  filter(Diversity != "Biomass")%>%
  filter(Diversity != "Evenness") 

partial_deviance_data=subset(partial_deviance_list, Predictor!="All")

diversity_order = c("Richness", "Simpson", "Shannon", "Functional")

partial_deviance_data= partial_deviance_list %>%
  filter(Predictor != "All") %>%
  mutate(Diversity = factor(Diversity, levels=diversity_order))

partial_deviance_explained = 
  ggplot(partial_deviance_data,aes(x= Diversity, y= Partial_Deviance*100, fill=Predictor))+
  geom_bar(position="dodge", color="black", stat = "identity")+
  geom_errorbar(aes(max=(Partial_Deviance+Partial_Deviance_SE)*100,
                    min=(Partial_Deviance-Partial_Deviance_SE)*100),
                  width=0.3,size=0.6, position=position_dodge(width=0.9))+
    labs(x="", y="Total % Deviance Explained\n")+
    #scale_fill_manual(values=c("grey50","grey80","white"))+
    #theme_bw(base_size=18)+
  theme(
    legend.position="bottom", #right 
    legend.text=element_text(size=16, color = "white"),
    legend.key.size=unit(10,"mm"),
    legend.key.width = unit(14, "mm"),
    legend.background = element_rect(fill = "grey30"),
    legend.title = element_text(size=16, color= "white"),
    panel.background=element_rect(fill="grey30"), #black
    panel.grid.major=element_line("grey40"),#element_blank(),
    panel.grid.minor=element_blank(),
    axis.title.x=element_text(size=20),
    #axis.title.y=element_text(size=20),
    axis.text.y=element_text(size=20),
    axis.text.x=element_text(size=20),
    plot.title =element_text(hjust = 0),
    title=element_text(size=20))

ggsave(file="pp_partial_deviance_explained.png", partial_deviance_explained, width=8.5, height=11, path="big_csv/plots")

ggsave(file="pp_partial_deviance_explained.pdf", partial_deviance_explained, width=8.5, height=11, path="big_csv/plots")

```

```{r pie chart}

psu_common_less1 <- psu_family %>%
    group_by(COMNAME) %>%
    summarize(abundance_sum = sum(abundance)) %>%
    filter(abundance_sum != "0") %>% #removes 32 species 
  mutate(com_percent = (abundance_sum/sum(abundance_sum))*100) %>%
  mutate(com_percent=round(com_percent,4))
write_csv(psu_common_less1, "psu_common1.csv")

psu_common = read_csv("psu_common1.csv")

library(plotly)

abunpie =plot_ly(psu_common_less1, labels=~COMNAME, values =~com_percent, type="pie")

pie = './htmlwidget_abunpie.html'
saveWidget(abunpie, pie)




```